### ISSUE TITLE
User Story: Checkout

### ISSUE THREAD

**Issue by z-bruce** [darealstyl/TeamJ-soen341project2022#111]
"As a user, I want to be able to checkout with the items in my cart so that I may finalize and place my order."

___

### > **Story Point**

___

Story Points: 15
Explanation: Being able to checkout with the products in the user's cart is a key feature of shopping online. Without this feature, a user would not be able to order the items they have placed in their cart.

___

# **Acceptance Tests: Checkout**

## Successful case:
1. A user who is logged in, and has items in their cart, presses the checkout button from the cart page.
   - Expected output: The user is redirected to a page with a form where they may enter their shipping information.

2. On the shipping information page, the user enters their shipping information and presses next.
     - Expected output: The user is redirected to the payment method page.

3. On the payment method page, the user selects a valid payment method and presses checkout.
   - Expected output: The user is redirected to a page where they may review the contents of their order before the final check-out.

4. On the order review page, the user clicks Check Out.
   - Expected output: The user is redirected to the Order Summary page.

## Unsuccessful cases:
**Option 1**
1. A user, who is not logged in, has items in their cart, and presses the checkout button.
   - Expected output: The user is redirected to the Sign In page, so they can sign in before placing their order.

**Option 2**
1. A user who is logged in, and has items in their cart, presses the checkout button from the cart page.
   - Expected output: The user is redirected to a page with a form where they may enter their shipping information.

2. On the shipping information page, the user enters invalid shipping information and presses next.
     - Expected output: The user is prompted to enter valid shipping information.

**Option 3**
1. A user who is logged in, and has items in their cart, presses the checkout button from the cart page.
   - Expected output: The user is redirected to a page with a form where they may enter their shipping information.

2. On the shipping information page, the user enters their shipping information and presses next.
     - Expected output: The user is redirected to the payment method page.

3. On the payment method page, the user does not select a valid payment method and presses checkout.
   - Expected output: The user is told that they must select a payment method before proceeding.

# **Risks/Countermeasures**
**High Risk & High priority**

**Explanation**: It is of high risk and high priority because as developers we value the user's payment security. It is important for our users to have secure payment and the payment should be validated.

**Countermeasures**
1. **Risk**: The user could place an order without entering payment information.
   - **Countermeasure**: Make entering payment information mandatory before being able to place the order.
2. **Risk**: Security risk of payment processing.
   - **Countermeasure**: Use a trusted payment processing service.
___

- [x] #112
- [x] #113
- [x] #114
- [x] #115
- [x] #87 
- [x] #116

**Comment by louisa-lina** [comment]
Addition of the explanation of risk and priority
