### ISSUE TITLE
User story: Admin product list

### ISSUE THREAD

**Issue by z-bruce** [darealstyl/TeamJ-soen341project2022#135]
**Description**
----------------------------------------------------------------------------------------------------------------------------------------
"As an admin, I want to be able to view and manage all products listed on the website by the various sellers."

###  Story Point
-------------------------------------------------------------------------------------------------------------------------------------------
**Story Points**: 15
Explanation: The story point allocated for this user story is 15 because the admins need to be able to have access to the product to assist the seller in case of issues.

------------------------------------------------------------------------------------------------------------------------------------------
###  Tasks Breakdown
-------------------------------------------------------------------------------------------------------------------------------------------
- Any admin may view a list of all products listed on the website by the various sellers.
- Admin have the privilege to modify a product's information, or remove it from the website entirely.

-------------------------------------------------------------------------------------------------------------------------------------------
###  Acceptance Test
-------------------------------------------------------------------------------------------------------------------------------------------
## Successful case:
1. The admin user who is successfully signed in clicks on the Product List link in the header.
   - Expected output: The admin user is redirected to the Product List page, where all products listed by all sellers on the website are displayed in a table.

2. The admin user clicks on one of the page buttons to navigate to a certain page of the product table.
   - Expected output: The admin user is taken to the chosen page of the admin Product List.

3. The admin user clicks on a product's delete button in the admin Product List.
     - Expected output: The admin is prompted with a confirm message: "Are you sure you want to delete this product?"

4. The admin user clicks on "Yes" to delete the selected product.
   - Expected output: The selected product is deleted from the database.

## Unsuccessful case:
**Option 1** 
1. A user who is not an admin attempts to access the admin product list.
   - Expected output: The user is redirected to the Sign In page. 
 
**Option2**

1. An admin logs into his account 
2. The admin user clicks on one of the page buttons to navigate to a certain page of the product table.
3. The admin chooses the product he is interested in .
4. He checks the details of the product 
5. The admins decides to remove the product 
6. He clicks on the button to delete the item 
7. The item is not deleted
8. As a result, the product is not deleted and the stocks do not represent the accurate number of products available.

-----------------------------------------------------------------------------------------------------------------------------------------
###  Risks, Priority & Countermeasures.
----------------------------------------------------------------------------------------------------------------------------------------
**High Priority& High Risks:**: This user story is high risk and high priority because it is important for the admin to be able to manage all products in case of an issue. The admins need to back up the sellers and be a source of reference in case of issues for the seller.

**Comment by louisa-lina** [comment]
organization of the datas

**Comment by louisa-lina** [comment]
Addition of labels , modifications of risk , explanation of user story
