### ISSUE TITLE
Users can register for an account

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#14]
"As a new user, I want to be able to register for an account so that I can log in to the website."
_______________________________________________________________________________________________________________________________

###  >  **Story Point**

_______________________________________________________________________________________________________________________________

Story Points: 15

______________________________________________________________________________________________________________________________

###  >  **Tasks Breakdown**

____________________________________________________________________________________________________________________________________

- [ ] When the user arrives at the signup page to create their account, they will be presented with 4 fields of a form they must fill out along with a create account button.

- [ ] The first form requires you to fill out your full name.

- [ ] The second form asks you to fill in the email you wish to use to log in to your account. The email must be a valid account that you can access in case of a forgotten password or other notification.

- [ ] The third form to be filled out is the password you would like to choose for your account. The password is recommended to have at least 1 uppercase letter, 1 number, and 1 special character. The password must also be at least 8 characters long, but not longer than 20 characters.

- [ ] The final form to be filled out is the confirm password, which is just a retype of the password in the third form in order to confirm that you have correctly entered your password before committing to creating your account.

- [ ] Once all the forms have been filled out, the user may submit the form by pressing the Create Account button.

- [ ] If the user has improperly filled out any of the fields, that field will turn red and indicate what the user must do in order to proceed, such as entering a valid email or password.

- [ ] If all the forms have been filled out properly then the form will submit and the user will be directed to a confirmation page that displays the confirmation of the creation of the account. The new user's account will be entered into the database. The user will then be able to proceed to the Sign In page where they can sign in to their new account with the username and password they just signed up with.

_______________________________________________________________________________________________________________________________

# **Acceptance tests for feature: Signing up for an account.**

## Successful case:
1. The user enters the website and clicks the Sign Up page button.
   - Expected output: The user is redirected to the Sign Up page.

2. The user provides the required information: first name, last name, email address, password, password confirmation, and whether they are signing up for a Seller or Buyer account.

3. The user clicks the Sign Up button, and the entered information that they entered is valid.
     - Expected output: The user's registration request is received and their chosen account information is stored in the database of users.

## Unsuccessful cases:
**Option 1** 
1. The user enters the website and clicks the Sign Up page button.
   - Expected output: The user is redirected to the Sign Up page.

2. The user provides the required information: first name, last name, email address, password, password confirmation, and whether they are signing up for a Seller or Buyer account.

3. The user clicks the Sign Up button, and but their passwords don't match.
     - Expected output: The user is notified that the passwords don't match, and is prompted to try again. 

**Option 2** 
1. The user enters the website and clicks the Sign Up page button.
   - Expected output: The user is redirected to the Sign Up page.

2. The user provides the required information: first name, last name, email address, password, password confirmation, and whether they are signing up for a Seller or Buyer account.

3. The user clicks the Sign Up button, and their password does not meet the security criteria.
     - Expected output: The user is notified that their password is not strong enough, and is prompted to try again. 

**Option 3** 
1. The user enters the website and clicks the Sign Up page button.
   - Expected output: The user is redirected to the Sign Up page.

2. The user provides the required information: first name, last name, email address, password, password confirmation, and whether they are signing up for a Seller or Buyer account.

3. The user clicks the Sign Up button, but an account with this email address already exists.
     - Expected output: The user is notified that an account with this email address already exists, and is prompted to try again.

**Option 4** 
1. The user enters the website and clicks the Sign Up page button.
   - Expected output: The user is redirected to the Sign Up page.

2. The user does not fill out all of the required information (first name, last name, email address, password, password confirmation, and whether they are signing up for a Seller or Buyer account).

3. The user clicks the Sign Up button.
     - Expected output: The user is notified that they must fill out all details in the form, and is prompted to try again.

# **Risks/Countermeasures**
1. **Risk**: Users using passwords that are too simple and easily guessed is a security risk. 
   - **Countermeasure**: The system will prompt the user to write a password until they write a strong password. The strong password will need to be composed of at least 1 capital letter, 1 number and should have a minimum length of 8.

2. **Risk**: Users trying to create multiple accounts with the same email address would cause inconsistencies with the website functionality.
   - **Countermeasure**: The system prompt will not allow the user to register with an email that is attached to an existing account.
____
### > **Priority & Risk**
______________________________________________________________________________________________________________________________
**High priority** & **high Risk**: The ability of the user to register for an account is a necessity and a **core feature**. This feature gives the user a personalized experience and gives them the ability to purchase a product.

**Comment by louisa-lina** [comment]
I added the label high priority and high risk for this user story. Can someone please verify the comment added to the description ?

**Comment by z-bruce** [comment]
> I added the label high priority and high risk for this user story. Can someone please verify the comment added to the description ?

@louisa-lina  Comment verified and approved

**Comment by louisa-lina** [comment]
I added some styling to organize it and will soon add the informations

**Comment by CarsonSSk** [comment]
@louisa-lina Ok sounds good. Thanks.
