### ISSUE TITLE
User can browse products

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#18]
"As a user, I want to be able to view the different products and find what I'm looking for."

_______________________________________________________________________________________________________________________________

###  >  **Story Point**

_______________________________________________________________________________________________________________________________

Story Points: 15

Explanation : Due to this feature being critical for browsing through the site for products. It is important as it will link to the features of the cart in the future, as well as be the main navigating page the user will spend the most time on. Interaction here is key.

_________________________________________________________________________________________________________________________________

###  >  **Tasks Breakdown**

____________________________________________________________________________________________________________________________________

- [ ] At the top of the product page, the category path of the product is shown (ex: Electronics > Camera, Photo & Video > Digital Cameras). The user can click on any of these categories to navigate to that category page.

- [ ] A photo of the product is shown. Below the photo are preview thumbnails of other photos of the product (if applicable). The user can click on these thumbnails to view the other photos of the product.

- [ ] A search bar is available for the user to search for the product he wants. He can click on the product he wants and he will be relocated to the item page. 

- [ ] The name of the product is shown in a bold, large font. Below the name, the product rating is shown on a scale of 5. The unit price of the item is displayed.

- [ ] If applicable to the product being viewed, the user is able to select different options for the product (ex: color, size).

- [ ] If an option is not available (due to being out of stock, or for another reason), the option will still be visible, but is grey and cannot be selected.

- [ ] Below the product options, a description of the product is shown, containing relevant information about the product.

- [ ] At the bottom of the product page there is an "Add to cart" button. Next to this button, there is a quantity field, which can be used to modify the quantity of the item to be added to the cart. The default value of this field is 1.

________________________________________________________________________________________________________________________________

## **>  Acceptance Test**

____________________________________________________________________________________________________________________________________

**Sucess:**

The users enter the website 
The users have access to all the products 
In each row and each collum, there is a product. 
The name of the product is written and a picture of it is shown 
The user can go on the search bar and write the name of the product they want 
They click on the product they want.
They can see a description of the product, the price, and the availability of the product. 
As a result, the user can browse the products and make a conscious decision of the product they want to buy.

**Failure:**
The users enter the website.
There is a malfunction.
The browsing page is either non-complete or completely non-accessible to the users. 
The users are lost. There is not enough information for them to make a conscious decision.

__________________________________________________________________________________________________________________________________

### > **Risks, Priority & Countermeasures.**

______________________________________________________________________________________________________________________________
**High Priority** & **High risk**: The product page is a core feature. It is a necessity because it is in the right of the user to have detailed information on the product he might purchase. It is the main feature that customers look for. Therefore, it is a high priority feature and its malfunction represents a high risk for the website.

**Countermeasures:** 

1. In the case of a failure of the browsing page due to a malfunction or a bug, the user will have access to the contact information of the sellers to get in touch and report the issue. 
2. An electronic pamphlet with all the products will be accessible to users. 
3. The user can view all the products digitally on the pamphlet, with prices and deals.
4. A report will be placed under issue to resolve the bug reported by the user
5. The user may place an order through the means of contacting the company and the admin will be able to place the order on their side.

________________________________________________________________________________________________________________________________

**Comment by louisa-lina** [comment]
Hey ! I added a comment in the description to justify the use of a high risk and high priority label for the : User can navigate the Product Page user story.

**Comment by CarsonSSk** [comment]
I agree with the risk and priority levels mentioned above. Thank you!

**Comment by louisa-lina** [comment]
Hi !
I changed some of the structure, I added the countermeasures and the acceptance test. Can you give me your opinion and tell me if I should improve some stuff. Thank you

**Comment by harismah** [comment]
I agree with the descriptions provided and the information is organized in an excellent manner. I agree with the description for the above story points, tasks, acceptance tests. But I believe for the countermeasure we should include something we as developers can do. Example create an option for admins to place order on behalf of the user after providing them a flyer/pamphlet to view the items

**Comment by harismah** [comment]
Please take a look at the above suggestion, and let me know what you think

**Comment by louisa-lina** [comment]
I think it's perfect . Thank you for your review .

**Comment by z-bruce** [comment]
This user story has been implemented in pull request #82 : from the browse page, users can view all available products, and click on a product to view its individual page and obtain more information about it
