### ISSUE TITLE
Sellers can add an item to their inventory

### ISSUE THREAD

**Issue by z-bruce** [darealstyl/TeamJ-soen341project2022#19]
"As a seller, I want to be able to add additional items to my inventory"

_______________________________________________________________________________________________________________________________

###  >  **Story Point**

_______________________________________________________________________________________________________________________________

Story Points: 15

Explanation: The seller is an important user. Our website revolves around the principle of buying and selling. The ability of the seller to add additional items is important for the functioning of our website and gives the user a vast variety of choices.
Moreover, these features assure us that the website will have items available. This feature is high risk and high priority and deserves a 15 point. 

______________________________________________________________________________________________________________________________

###  >  **Tasks Breakdown**

___________________________________________________________________________________________________________

- [x] #81
- [x] #58 
- [x] #59
- [x] #127
- [x] #128

The information that the seller can enter for a product is: 

Name
Brand
Image
Category
Description 
Price
CountInStock

___________________________________________________________________________________________________________
Below are subtasks which were initially part of the user story, but after discussing with the team working on this user story we determined that they are outside the scope of this Sprint. In practice, these would be considered as enhancements that could be implemented in future Sprints.
 
-  #60
-  #61
-  #62
-  The user will be redirected to the information page about this product where they may modify the information about the product, as well as detail the price and quantity of the item they wish to publish. Once this is finished, the user will press the 'Submit' button to publish their product for review by the Admins.
- #63
-  In this case, the user will first be asked to select a category they wish to publish their product in. Next, the user will have to complete all of the information required to publish the product. This information includes, but is not limited to: title, UPC, brand, description, and photo of the product. Once the information is completed, the price and quantity may be detailed and the user may press the 'Submit' button to publish their product for review by the Admins.
-  #64

___________________________________________________________________________________________________________

## **>  Acceptance Test**

___________________________________________________________________________________________________________

**Success:** 
The seller logs into his account 
He enters his page 
He selects the option of adding a product 
He chooses from the option  : Do you wish to choose to add a product that already exists or a new product. 
**_Option 1_** 
the user chooses to add an existing product he has to choose the product he wants to add
He will be then redirected to the item page 
He will have the option to change the information of the product: quantity, price, description, and more. 
He changes all the field requested perfectly
He will click on the Save button. 
The changes are sent to the admins.
The admins verify if there are no issues and accept the request. 
The seller has new products to sell and the customers new products to buy. 
_**Option 2**_
The seller selects the option of adding a new product 
The user has to choose in what category will his product be published product.
After choosing the category, the seller has to enter all the information related to his product such as 
1. The name of the item 
2. The UPC
3. The brand
4. A description of the product 
5. A picture of the product.
6. The price of the product
7. The number of items available.

All of the information was perfectly filled. 
The seller provided complete information and a high-quality picture of the product.
The seller's request was verified by the admins.
The request is accepted.
The seller has new products to sell and the customers new products to buy. 

**Failure:**
The seller enters his account 
He chooses the option of adding a product 
The system gives him the options of adding a new product or an existing one 
The user has to fill all the fields.
The user forgets some information
The system does not notify him that he forgot a field.
He submit his request to be verified by admins 
The time is taken for them to verify it and contact the seller for him to give the new information again takes a long time. 
The product is left unavailable for a long time the seller might lose money, the customers will wait a long time for their desired product and the website might lose a seller due to the long time to validate the request. 

___________________________________________________________________________________________________________

### > **Risks, Priority & Countermeasures.**

___________________________________________________________________________________________________________

**High Priority**& **High Risk:** The ability of the sellers to add an item to their inventory is of high importance and high risk because it is like that that we assure that our website always has items to be bought. The inability to let the user add items can bring the website to a critical situation where the goal of our website is in danger. 

**Countermeasures:**
1. To assure that the request is processed quickly and the seller can add items, a team will be solely responsible to have contacts with the sellers, verifying their request, and making the changes on the seller's page. 

2. Prompt the user to write all the information about his product. The seller would not be able to submit his request until all information are complete. If the user forgets one of the detail. The field of the missing information will pop out in red. This countermeasure will hopefully speed up the process of request validation from the admins since all the documentation is complete.

**Comment by louisa-lina** [comment]
Hi , I changed the styling to make it more organized  I will add some informations after.

**Comment by louisa-lina** [comment]
i added the story points and the explanation I will soon continue more

**Comment by z-bruce** [comment]
All subtasks complete, user story completed through PR #131
