### ISSUE TITLE
User can add items to their virtual shopping cart 

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#20]
"As a user, I want to be able to add my items to my shopping cart"

_______________________________________________________________________________________________________________________________

###  >  **Story Point**

_______________________________________________________________________________________________________________________________

Story Points: 15

Explanation :The users ' ability to add items to their cart is a core feature of our project . The main goal of the website is to permit users to buy and sell products without this features the whole purpose of our project fails .Therefore, the addition of items to the shopping cart is worth 15 points . 

______________________________________________________________________________________________________________________________

###  >  **Tasks Breakdown**

____________________________________________________________________________________________________________________________________

- [x] #45

- [x] #46

- [x] #47

- [x] #48

- [x] #49

- [x] #50

- [x] #51

- [x] #52

- [x] #53

- [x] #54

- [x] #55

- [x] #56

- [x] #57

_______________________________________________________________________________________________________________________________

## **>  Acceptance Test**

_________________________________________________________________________________________________________________________________

**Success:**
The user logs into his account 
He browses the website 
He clicks on a product of his interest 
The user reads the information such as the description, the price, and the availability. 
The product satisfies the user and is in stock. 
The user clicks on the button add to add the product. 
The product is successfully added to the cart.
The user repeats this process as many times as he desires 
The user sees the amount in his cart 
The amount Is accurate
The user is ready to process the payment
The user put in his payment information and shipping information
The user receives a notification of confirmation for his order.
The client is satisfied with the process

**Failure:**
Option1
The user logs into his account 
He browses the website 
He clicks on a product of his interest 
The user reads the information such as the description, the price, and the availability. 
The product satisfies the user and is in stock. 
The user clicks on the button add to add the product. 
The product is not added to the cart 
Option 2
The user logs into his account 
He browses the website 
He clicks on a product of his interest 
The user reads the information such as the description, the price, and the availability. 
The product satisfies the user and is in stock. 
The user clicks on the button add to add the product. 
The product is successfully added to the cart.
The user repeats this process as many times as he desires 
The user sees the amount in his cart 
The amount is not accurate
Option 3 
The user logs into his account 
He browses the website 
He clicks on a product of his interest 
The user reads the information such as the description, the price, and the availability. 
The product satisfies the user and is in stock. 
The user clicks on the button add to add the product. 
The product is successfully added to the cart.
The user repeats this process as many times as he desires 
The user sees the amount in his cart 
The amount is accurate 
The user is ready to process the payment
The user put in his payment information and shipping information
However, his payment option even valid are not well processed 
In another case, the Shipment information doesn't match the required fields
The payment process is not accepted 
The user cannot buy the products 
The user is not satisfied with the process.

___________________________________________________________________________________________________________________________________

### > **Risks, Priority & Countermeasures.**

______________________________________________________________________________________________________________________________
**High priority** & **High risk**: The addition of the products to the cart is a **core feature** and without a doubt a necessity. The addition of the product to the cart is **a must** to purchase a product. Without it , the customer will not be able to purchase a product via the website. **Therefore**, it is a high priority and high-risk feature. 

Countermeasures:
1. Admins will be able to reserve an order from the back end in case of an issue. The user can send a notification to the admins with the wanted products the product will be then reserved for them. In the back end, the products will be associated and reserved for a specific user. The user will then be able to see it on their profile.

2. A team will be assigned to perform test bugs every 3 hours and the team will take into consideration the previous bugs mentioned by the users.

**Comment by louisa-lina** [comment]
I added a comment to justify the addition of the high-risk & high priority label.

**Comment by CarsonSSk** [comment]
I agree with the risk and priority levels. Thanks!

**Comment by louisa-lina** [comment]
I added some styling to organize the story so we can better enter the information in an organized way after

**Comment by louisa-lina** [comment]
I added the acceptance test and the explanation for the story I will soon add the countermeasures

**Comment by louisa-lina** [comment]
Addition of countermeasures
