### ISSUE TITLE
User Story: browsing for items

### ISSUE THREAD

**Issue by z-bruce** [darealstyl/TeamJ-soen341project2022#30]
As a user, I want to be able to browse for items so I can decide what I want to purchase.

Story points: 15

- [x] #31
- [x] #38
- [x] #150
- [x] #37
- [x] Acceptance test 3: Being able to go from a browsing page to a specific product item page

**High Priority** & **High Risk**: Browsing items is a **core feature.** It represents one of the main goals of the website. The user needs to see the products and browse them to have a global image of what is sold.

# **Acceptance tests for core feature number 1, browsing for available items.**

## Successful cases:
1. From the Browsing Page, the user clicks on a product card.
   - Expected output: The user is redirected to that product's Product Page.

2. From the Browsing Page, the user clicks on a page number button at the bottom of the screen.
   - Expected output: The user is taken to the page that they clicked on.

3. From the Browsing Page, the user enters a query into the search bar and presses the 'Search' button.
   - Expected output: The user will be shown products whose Name, Category or Brand matches the search query (if any exist).

**Comment by CarsonSSk** [comment]
Hey team, I associated 15 story points for this user story. Please modify it if it doesn't represent the actual workload. Thanks. @haris2055 @louisa-lina @jaskiratkaur1906 @Nijaoui-Wassim

**Comment by louisa-lina** [comment]
I added a comment on the description to justify the use of a high risk & high priority label .

**Comment by z-bruce** [comment]
> I added a comment on the description to justify the use of a high risk & high priority label .

Comment/risk/priority approved

**Comment by harismah** [comment]
Successfully completed all the required tasks for this user story of browsing items.
