### ISSUE TITLE
Implementing product page

### ISSUE THREAD

**Issue by harismah** [darealstyl/TeamJ-soen341project2022#38]
The product page shows the details of the product including a written description of the product, the price, the availability of the product and an image of the product . 

**High Priority** & **High Risk** : The ability of the user to browse the product page and see the details of the product desired is a core feature and a necessity for the success of the purchase and the website as a whole.

**Comment by louisa-lina** [comment]
Done successfully

**Comment by harismah** [comment]
Thanks for checking

**Comment by louisa-lina** [comment]
no problem :)

**Comment by louisa-lina** [comment]
Addition of a label of high-priority & high-risk.

**Comment by harismah** [comment]
Confirmed priority assigning checked.

**Comment by louisa-lina** [comment]
Addition of a comment to the general description.
