### ISSUE TITLE
New Users can create an account 

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#40]
"As a user, I want to be able to create a new account"

_______________________________________________________________________________________________________________________________

###  >  **Story Point**

_______________________________________________________________________________________________________________________________

Story Points: 15

Explanation: The creation of an account is extremely important it gives the users a personal experience on the website.
The user needs an account to be able to purchase products . The main goal of the website is selling and buying so 
the creation of an account to be able to buy items is extremely important. 

______________________________________________________________________________________________________________________________

###  >  **Tasks Breakdown**

____________________________________________________________________________________________________________________________________

- [x] When the user arrives at the signup page to create their account, they will be presented with 4 fields of a form they must fill out along with a create account button.

- [x] The first form requires you to fill out your full name.

- [x] The second form asks you to fill in the email you wish to use to log in to your account. The email must be a valid account that you can access in case of a forgotten password or other notification.

- [x] The third form to be filled out is the password you would like to choose for your account. The password is recommended to have at least 1 uppercase letter, 1 number, and 1 special character. The password must also be at least 8 characters long, but not longer than 20 characters.

- [x] The final form to be filled out is the confirm password, which is just a retype of the password in the third form in order to confirm that you have correctly entered your password before committing to creating your account.

- [x] Once all the forms have been filled out, the user may submit the form by pressing the Create Account button.

- [x] If the user has improperly filled out any of the fields, that field will turn red and indicate what the user must do in order to proceed, such as entering a valid email or password.

- [x] If all the forms have been filled out properly then the form will submit and the user will be directed to a confirmation page that displays the confirmation of the creation of the account. The new user's account will be entered into the database. The user will then be able to proceed to the Sign In page where they can sign in to their new account with the username and password they just signed up with.
_______________________________________________________________________________________________________________________________

## **>  Acceptance Test**

________________________________________________________________________________________________________________________________

**Success:**
The user enters the website 
He browses some of the product 
He decides that he wants an account to buy products 
He goes on the Sign Up page 
He provides the required information such as : his first name,last name, email address, his password, and password confirmation. 
The information are saved and secured . 
The user has an account he can use . 

**Failure:**
The user enters the website 
He wants to register as a new user. 
He writes all his information 
He chooses a password.
The password is his first name 
The user's account is endangered without him knowing.
A malicious server enters his account and has access to his information and purchases. 
In another case , 
There is a mismatch between the two password .
The email is invalid .
In another case, 
The user tries to log in after registering 
However the user is still unable to access his profile 
The information were not saved during the creation of the account 
The user has no account 
He was unable to register and use his account to have a personalized experience and buy products  . 

____________________________________________________________________________________________________________________________________

### > **Risks, Priority & Countermeasures.**

______________________________________________________________________________________________________________________________

**High Risk & HIgh priority:**The creation of an account is of high priority. A user needs an account to purchase products which is the main goal of our website. Moreover, it is of high risk an account has important information about the users . All of the user's information should be secured and protected against malicious attacks. 

**Countermeasures:**
1.The system will prompt the user to write a password until he writes a strong password .
The strong password will be composed of a capital letter , a special character , 1 number and  should have a length of 8 .
2.The system prompt the user to rewrite his password in the case of a mismatch In between the passwords .
3.The system prompt with a message explaining the situation to the user until he enter an existing email .A confirmation number will be sent to the email .

**Comment by CarsonSSk** [comment]
"As a user, I want to be able to create a new account"

- [ ] User should be able to enter profile information
- [ ] User should be able to save profile information by clicking the submit button

**Comment by louisa-lina** [comment]
Hi I wrote the story points explanation , the acceptance testing , the explanation of the risk and priority and some countermeasures . Can you please verify if everything is ok .Please feel free to change stuff to improve it if you see some issues.

**Comment by Nijaoui-Wassim** [comment]
Hey Louisa, thanks a lot for taking the time. Everything looks great! :D

**Comment by Nijaoui-Wassim** [comment]
User Login features is created and merged with main

**Comment by louisa-lina** [comment]
no problem Wassim :)

**Comment by z-bruce** [comment]
implemented via pull request #84 : users can sign up for an account for the register page, and once an account has been created they are able to sign in to their account
