### ISSUE TITLE
User should be able to enter profile information

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#43]
High Risk & High Priority subtask : The user's ability to enter their information to sign in or sign up is a core feature of the user story . It is a necessity for creation and use of a user profile .

**Comment by louisa-lina** [comment]
Addition of a description to explain the high risk and High priority label added. Could you please verify? :)

**Comment by CarsonSSk** [comment]
Yes everything looks good. Thanks for the addition.

**Comment by z-bruce** [comment]
implemented via pull request #84 : users can sign up for an account for the register page, and once an account has been created they are able to sign in to their account
