### ISSUE TITLE
From the cart window, a list of items currently in the cart is visible. Each item is displayed in the same amount of space, with divider lines separating the items.

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#47]
**Medium Priority** & **low Risk**: It is important to see a list of the item. It can help the user to make an informed choice on his purchases . However, the styling is of low risk and low priority.

**Comment by louisa-lina** [comment]
I added a description to justify the label of low risk & medium priority added.

**Comment by CarsonSSk** [comment]
Viewed and reviewed. Everything looks great.

**Comment by louisa-lina** [comment]
I added it as low priority it's all about design not functionability

**Comment by z-bruce** [comment]
resolved by #98, #99 and #101 (which added cart screen and cart functionality)
