### ISSUE TITLE
The first prompt the user will encounter will be to answer whether you wish to add a product that already exists on the website or an entirely new product.

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#60]

**Comment by z-bruce** [comment]
After discussing with the team working on the core feature that this subtask belonged to (#19 Sellers can add products to their inventory), we decided that this subtask is not necessary to be a part of the user story at this time. Sellers will be able to add a product by just entering its information, and not going through the additional prompts to select a product that already exists.
