### ISSUE TITLE
Should the user select 'Add an existing product', the user will be asked to search for the product.

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#61]
**Low Priority** & **Low Risk**: The feature of adding an existing product is an interesting **enhancement** to better the user experience and make his purchase of products easier. However, it is an enhancement **rather** than a core feature.

**Comment by louisa-lina** [comment]
I added a comment to justify the use of the label: low risk and low priority.

**Comment by CarsonSSk** [comment]
I agree with the priority and risk assigned to this issue. Thanks!

**Comment by louisa-lina** [comment]
No problem :)

**Comment by z-bruce** [comment]
After discussing with the team working on the core feature that this subtask belonged to (#19 Sellers can add products to their inventory), we decided that this subtask is not necessary to be a part of the user story at this time. If there were going to be additional sprints, this could be considered as an enhancement for the future.
