### ISSUE TITLE
If the product is found, then the user can select the product and press the 'Add this product' button.

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#62]
The user will be redirected to the information page about this product where they may modify the information about the product, as well as detail the price and quantity of the item they wish to publish. Once this is finished, the user will press the 'Submit' button to publish their product for review by the Admins.

**Comment by z-bruce** [comment]
After discussing with the team working on the core feature that this subtask belonged to (#19 Sellers can add products to their inventory), we decided that this subtask is not necessary to be a part of the user story at this time. If there were going to be additional sprints, this could be considered as an enhancement for the future.
