### ISSUE TITLE
If the product is not found, then the user will have to select 'The product I wish to add does not exist yet'.

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#63]
In this case, the user will first be asked to select a category they wish to publish their product in. Next, the user will have to complete all of the information required to publish the product. This information includes, but is not limited to: title, UPC, brand, description, and photo of the product. Once the information is completed, the price and quantity may be detailed and the user may press the 'Submit' button to publish their product for review by the Admins.

**Medium priority** & **low risk**: It is an important and interesting feature to add to **enhance** the seller experience. It can create diversity in the website. By this fact, the customers have the opportunity to buy a diversified set of products. Indeed, it gives freedom to the users ( in this case: the sellers) to customize their store and appeal to a greater range of customers.

**Comment by louisa-lina** [comment]
I added a comment in the description to justify the use of the medium priority and low-risk label.  What are your thoughts on the matter?

**Comment by CarsonSSk** [comment]
Reviewed and approved!

**Comment by z-bruce** [comment]
After discussing with the team working on the core feature that this subtask belonged to (#19 Sellers can add products to their inventory), we decided that this subtask is not necessary to be a part of the user story at this time. If there were going to be additional sprints, this could be considered as an enhancement for the future.
