### ISSUE TITLE
User must be able to leave a review on a product

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#65]
"As a user, I want to be able to give my opinion on its quality."

_______________________________________________________________________________________________________________________________

###  >  **Story Point**

_______________________________________________________________________________________________________________________________

Story Points: 8

Explanation: We allocated the number 8 for this user story because this story is important for the user so that he can make 
a conscious decision on his purchases and the seller as well as another user can get feedback. For these reasons, this is 
an important story. However, it is of low risk; the website is still completely functional without it but it's a good feature to have to be fair with the users and give feedback to the sellers on their products.

______________________________________________________________________________________________________________________________

###  >  **Tasks Breakdown**

____________________________________________________________________________________________________________________________________

- [x] #66
- [x] #67
- [x] #68
- [x] #120
- [x] #121

_______________________________________________________________________________________________________________________________

## **>  Acceptance Test**

_________________________________________________________________________________________________________________________________

**Success:**

the user logs in to his account 
He then navigates to the browsing page. 
He searches an item he's interested in or simply finds it on the browsing page 
The user clicks on the item that interests him. 
He is directed to the product page of the item 
He goes down and clicks on leave a review.
He can add the number of stars he rates the product . 
He writes a review on why he likes or dislikes the product .
He sends the review 
The review is saved and everyone can see it .
The users and the sellers can read the review and make conscious changes and decisions concerning the product. 

**Failure:**
The user enters the product page 
He wants to leave a review.
The feature is not functional.
He cannot access it.
In another case, he could access it 
He writes his review 
Sadly, he is unable to save it 
The user was unable to leave a review or see other users' reviews.
The user is unable to make a conscious decision on his purchases and give feedback to the sellers or other users. 

___________________________________________________________________________________________________________________________________

### > **Risks, Priority & Countermeasures.**

______________________________________________________________________________________________________________________________

**High Priority**& **Low Risks**: The rating option is an important feature. The user has a right to give his opinion on the object he purchased. Moreover, the user's reviews will help future customers to make an informed choice and will provide important feedback to the seller. 

**Countermeasures:** 
1. The user will be redirected to an error page where they will be invited to follow a set of instructions in order to submit their review. The set of instructions will show the user how to send their review to a support team via email. The support team will then save the user's review and post it for them when the issue is fixed. The team will send the user an email once the review is successfully posted.
2. The error page will also provide a list of instructions for a second solution, which is to contact the admin directly via email and to let him know about the technical difficulties. The admin will then either fix the problem or delegate the task to an employee and will contact the user once the situation is dealt with.

**Comment by louisa-lina** [comment]
Addition of a comment in the description to explain the high-priority label.

**Comment by CarsonSSk** [comment]
Yes this is a high-priority issue. Thanks.

**Comment by louisa-lina** [comment]
no problem

**Comment by louisa-lina** [comment]
I organized the way we should detail our stories. I will write the information soon

**Comment by louisa-lina** [comment]
I added the story points and the explanation, the acceptance tests. I will do the countermeasures afterward. Can you please see if its all good and give me your opinion.

**Comment by CarsonSSk** [comment]
I added the countermeasures for this user story.
