### ISSUE TITLE
Scheduling of the group meetings in advance 

### ISSUE THREAD

**Issue by louisa-lina** [darealstyl/TeamJ-soen341project2022#77]
Description: Meetings give us the possibility to talk about our progress, certain issues and make a consensus on diverse features of the project. It is a key point to create harmony in the team. Scheduling meetings which fit everyone's busy schedule can be challenging.Most of us had important midterms this week .Therefore , it is important to make time and find solutions to manage our times to complete our project .

Importance: Scheduling meetings is a **high-priority** task. Therefore, preparing them in advance is important and a solution must be put in place to assure that an acceptable amount of meetings take place. 

**Countermeasure**: To achieve the task, it is important for each member of the team to give their availability. Based on their availability, we will schedule at least one long meeting per week. To accommodate everyone's schedule and needs, other meetings will take place but might be shorter to assess progress and talk about minor issues.  In our case, small meetings of 15 min every 2 days can easily be done. Indeed, the addition of smaller meetings is easier to manage and will be beneficial for our teamwork.

**Comment by louisa-lina** [comment]
Hi! I added a new issue with a description, level of importance and countermeasures to help us better achieve it.Can you please verify this issue? Thank you :)

**Comment by Nijaoui-Wassim** [comment]
verified the level of importance and countermeasures and I agree with you.

As of for the availability, I am free every evening anytime

**Comment by louisa-lina** [comment]
Thank you for your comment!

**Comment by z-bruce** [comment]
the group meetings were scheduled in advance
