### ISSUE TITLE
Even Distribution of Tasks 

### ISSUE THREAD

**Issue by louisa-lina** [darealstyl/TeamJ-soen341project2022#78]
Description: In a team project, the workload must be distributed evenly to enhance the individual team members' performance of each member and therefore benefit the whole group's performance. Moreover, all members **must** agree to the distribution of tasks and they **must** have the possibility to choose tasks that fit their skills and field of expertise. 

Importance: It is a **high-priority** task. Therefore, appropriate actions should be performed to ensure that all members are satisfied with the distribution of the tasks 

Countermeasure: To achieve a consensus, an important meeting will take place before the start of the sprint. Each member will have to read the set of guidelines on his own. When all team members will be done, the team leader or a volunteer will read the guidelines to the team. The team will discuss and ask questions on the requirements. The set of tasks will be then created and the number of tasks will be divided **evenly**. Each member will choose a certain amount of tasks that fit them. In the case where two-member want to work on the same task, the option to form a small team for that task will be given. Indeed, the goal is to minimize issues and keep the harmony of the team for a better teamwork and thus better results.

**Comment by louisa-lina** [comment]
Hi ! I added an issue with a description, a level of importance, and countermeasures to achieve the task. What are your thoughts on the issue?

**Comment by z-bruce** [comment]
> Hi ! I added an issue with a description, a level of importance, and countermeasures to achieve the task. What are your thoughts on the issue?

Very detailed description and countermeasure, I agree with all that you said. Thank you!

**Comment by louisa-lina** [comment]
Thank you for your comment :)

**Comment by Nijaoui-Wassim** [comment]
I agree with you, that will definitely be the best approach to minimize the  number of issues and increase our productivity as you mentioned

**Comment by Nijaoui-Wassim** [comment]
meeting took place and tasks were distributed and we are currently working on them.
