### ISSUE TITLE
User can select various payment methods to purchase product

### ISSUE THREAD

**Issue by CarsonSSk** [darealstyl/TeamJ-soen341project2022#87]
"As a user, I want to be able to have the option to use different payment methods to purchase a desired product."

- [x] User must have the option to pay using a credit card
- [x] User must have the option to pay using PayPal

Story points: 5

___

# **Acceptance Tests: Selecting payment method**

## Successful cases:
**Option 1**
1. A user who is logged in and has items in their cart who is in the checkout process, arrives at the payment method screen.
   - Expected output: The user is presented with the option to select either PayPal or Credit Card.

2. The user selects PayPal.
     - Expected output: The user is able to proceed to the Order Confirmation screen.

**Option 2**
1. A user who is logged in and has items in their cart who is in the checkout process, arrives at the payment method screen.
   - Expected output: The user is presented with the option to select either PayPal or Credit Card.

2. The user selects Credit Card.
     - Expected output: The user is able to proceed to the Order Confirmation screen.

## Unsuccessful case:
1. A user who is logged in and has items in their cart who is in the checkout process, arrives at the payment method screen.
   - Expected output: The user is presented with the option to select either PayPal or Credit Card.

2. The user selects does not select a payment method and attempts to proceed to the Order Confirmation screen.
     - Expected output: The user is unable to proceed to the Order Confirmation screen and told that they must select a payment method to continue.

# **Risks/Countermeasures**
1. **Risk**: The user could place an order without entering payment information.
   - **Countermeasure**: Make entering payment information mandatory before being able to place the order.
2. **Risk**: Security risk of payment processing.
   - **Countermeasure**: Use a trusted payment processing service.

**Comment by louisa-lina** [comment]
It's perfect !
