### ISSUE TITLE
Sellers can modify an existing product in their inventory

### ISSUE THREAD

**Issue by z-bruce** [darealstyl/TeamJ-soen341project2022#90]
----------------------------------------------------------------------------------------------------------------------------------------
**Description**
----------------------------------------------------------------------------------------------------------------------------------------
"As a seller, I want to be able to modify the details of a product listed in my inventory"

---------------------------------------------------------------------------------------------------------------------------------------

###  Story Point
-------------------------------------------------------------------------------------------------------------------------------------------
**Story points: 10 points**
Explanation: It is important for the sellers to be able to modify the details of a product on their profiles . It is important for the seller's inventory to reflect an accurate representation of their stocks.

-------------------------------------------------------------------------------------------------------------------------------------------

###  Acceptance Test
-------------------------------------------------------------------------------------------------------------------------------------------
Success: 
The seller logins into his account 
The seller goes into his inventory 
He browses the products available in his inventory 
The seller chooses to view an item
The seller changes the details of his product 
The details are successfully saved 
As a result, the seller's inventory reflects an accurate representation of their stocks. 

Failure:
The seller logins into his account 
The seller goes into his inventory 
He browses the products available in his inventory 
The seller chooses to view an item
The seller changes the details of his product 
The details are not saved 
As a result, the seller's inventory does not reflect an accurate representation of their stocks. 

###  Risks, Priority & Countermeasures.
----------------------------------------------------------------------------------------------------------------------------------------
**High Priority and Medium Risks**
Explanation: It is essential for sellers on the website to be able to modify the information associated with a product in their inventory. For example, if the seller wishes to increase the price of a product, they must be able to modify the price associated with the product. It is important for both the user and the clients to have an accurate representation of what they can buy or sell .

**Comment by louisa-lina** [comment]
Addition of acceptance tests

**Comment by harismah** [comment]
I agree with the acceptance test and the description looks good, throughout
