### ISSUE TITLE
Sellers can delete a product from their inventory

### ISSUE THREAD

**Issue by z-bruce** [darealstyl/TeamJ-soen341project2022#91]
----------------------------------------------------------------------------------------------------------------------------------------
**Description**
----------------------------------------------------------------------------------------------------------------------------------------
"As a seller, I want to be able to remove a product from my inventory"

###  Story Point
-------------------------------------------------------------------------------------------------------------------------------------------
**Story points:** 10 Points
Explanation: The removal of a product by the seller on their inventory is an important feature because it is important for the seller and the clients to have an accurate representation of their stock. The seller needs to give an accurate display of his product availability both for him and the clients.

-------------------------------------------------------------------------------------------------------------------------------------------

###  Acceptance Test
-------------------------------------------------------------------------------------------------------------------------------------------
Success: 
The seller log in his account 
He clicks on his inventory 
He browse the products 
He clicks on his products of interest 
He changes the amount of product available
In this case, he decided to remove one of the items 
The amount is saved and show a reduction of the exact number desired by the seller 

Failure:
The seller log in his account 
He clicks on his inventory 
He browses the products 
He clicks on his products of interest 
He changes the amount of product available
In this case, he decided to remove one of the items 
Option 1 
He is unable to change the amount value of the items ; the buttons are not functioning 
Option 2: 
He changes the amount of product available
In this case, he decided to remove one of the items 
As a result , the amount is not saved and does not show a reduction of the exact number desired by the seller 

###  Risks, Priority & Countermeasures.
----------------------------------------------------------------------------------------------------------------------------------------
**High Priority and Medium Risk**

Explanation: It is essential for sellers on the website to be able to remove a product from their inventory. If the seller will no longer be carrying a certain product in their inventory to sell, they need to be able to remove the product so that no one can attempt to purchase it. It is of medium risk because in the worst case the admin can remove it from the back end

**Comment by louisa-lina** [comment]
Organized the informations

**Comment by louisa-lina** [comment]
Adition of acceptance tests

**Comment by louisa-lina** [comment]
modification of the risks and explanation

**Comment by louisa-lina** [comment]
story point and explanation done
